version: 0.2

phase:
  install:
    runtime-versions:
      docker: 18
      nodejs: 16
  pre_build:
    - echo Installation Dependencies
    - npm install
    - ${aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION}}

  build:
    - echo Build Information
    # - npm run test
    - npm run start
    - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
    - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    - echo Pushing the docker image
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
    - printf "[{"name":"%s", "image":"%s"}]" $CONTAINER_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json